captcha:
  key-long: 6
  img-width: 240
  img-height: 80
casbin:
  model-path: ./resource/rbac_model.conf
jwt:
  signing-key: gea
local:
  path: uploads/file
mysql:
  path: 127.0.0.1:3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: gin-element-admin
  username: root
  password: 123456
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: false
  log-zap: false
redis:
  db: 0
  addr: 127.0.0.1:6379
  password: ""
system:
  env: public
  addr: 8888
  db-type: mysql
  oss-type: local
  use-multipoint: false
zap:
  level: info
  format: console
  prefix: '[Gin-Element-Admin]'
  director: log
  link-name: latest_log
  showLine: false
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
